name: tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: install dependencies
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"

      - name: lint
        run: |
          python -m pip install ruff
          ruff check src --select F,E9

      - name: run tests
        run: python -m pytest -q tests
